/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WritingStackRouteImport } from './routes/writing/stack'
import { Route as WritingAiRouteImport } from './routes/writing/ai'
import { Route as BuildingProjectsRouteImport } from './routes/building/projects'
import { Route as BuildingAnimationsRouteImport } from './routes/building/animations'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WritingStackRoute = WritingStackRouteImport.update({
  id: '/writing/stack',
  path: '/writing/stack',
  getParentRoute: () => rootRouteImport,
} as any)
const WritingAiRoute = WritingAiRouteImport.update({
  id: '/writing/ai',
  path: '/writing/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildingProjectsRoute = BuildingProjectsRouteImport.update({
  id: '/building/projects',
  path: '/building/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildingAnimationsRoute = BuildingAnimationsRouteImport.update({
  id: '/building/animations',
  path: '/building/animations',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/building/animations': typeof BuildingAnimationsRoute
  '/building/projects': typeof BuildingProjectsRoute
  '/writing/ai': typeof WritingAiRoute
  '/writing/stack': typeof WritingStackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/building/animations': typeof BuildingAnimationsRoute
  '/building/projects': typeof BuildingProjectsRoute
  '/writing/ai': typeof WritingAiRoute
  '/writing/stack': typeof WritingStackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/building/animations': typeof BuildingAnimationsRoute
  '/building/projects': typeof BuildingProjectsRoute
  '/writing/ai': typeof WritingAiRoute
  '/writing/stack': typeof WritingStackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/building/animations'
    | '/building/projects'
    | '/writing/ai'
    | '/writing/stack'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/building/animations'
    | '/building/projects'
    | '/writing/ai'
    | '/writing/stack'
  id:
    | '__root__'
    | '/'
    | '/building/animations'
    | '/building/projects'
    | '/writing/ai'
    | '/writing/stack'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuildingAnimationsRoute: typeof BuildingAnimationsRoute
  BuildingProjectsRoute: typeof BuildingProjectsRoute
  WritingAiRoute: typeof WritingAiRoute
  WritingStackRoute: typeof WritingStackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writing/stack': {
      id: '/writing/stack'
      path: '/writing/stack'
      fullPath: '/writing/stack'
      preLoaderRoute: typeof WritingStackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writing/ai': {
      id: '/writing/ai'
      path: '/writing/ai'
      fullPath: '/writing/ai'
      preLoaderRoute: typeof WritingAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/building/projects': {
      id: '/building/projects'
      path: '/building/projects'
      fullPath: '/building/projects'
      preLoaderRoute: typeof BuildingProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/building/animations': {
      id: '/building/animations'
      path: '/building/animations'
      fullPath: '/building/animations'
      preLoaderRoute: typeof BuildingAnimationsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuildingAnimationsRoute: BuildingAnimationsRoute,
  BuildingProjectsRoute: BuildingProjectsRoute,
  WritingAiRoute: WritingAiRoute,
  WritingStackRoute: WritingStackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
